microservicAPI/UI/UI/Controllers/HomeController.cs
namespace UI.Controllers;

public class HomeController : Controller
{
    [HttpGet]
    public ActionResult Index()
    {
        ViewData["Title"] = "Home Page";

        return View("Index");
    }

    [HttpGet]
    public ActionResult Privacy()
    {
        ViewData["Title"] = "Privacy Policy";

        return View("Privacy");
    }

    [HttpGet]
    public ActionResult Error()
    {
        ViewData["Title"] = "Error";

        return View("Error");
    }
}

microservicAPI/UI/UI/Controllers/ProductsController.cs
namespace UI.Controllers;

public class ProductsController : Controller
{
    private readonly IProductService _productsService;
    private readonly INotifierService _notifierService;

    public ProductsController(IProductService userService, INotifierService notifierService)
    {
        _productsService = userService;
        _notifierService = notifierService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _productsService.GetAll();
        IncludeMessages();

        return View("Index", result);
    }

    [HttpGet("ProductDetails/{id}")]
    public async Task<IActionResult> ProductDetails(int id)
    {
        var result = await _productsService.GetProductById(id);

        IncludeMessages();

        return View("Details", result);
    }

    [HttpGet]
    public ActionResult Create()
    {
        return View("Create");
    }

    [HttpPost]
    public async Task<IActionResult> CreateProduct(ProductCreateModel user)
    {
        if (!VerifyModelState(user))
            return Create();

        var result = await _productsService.CreateProduct(user);

        return await Index();
    }

    [HttpGet("ProductEdit/{id}")]
    public async Task<IActionResult> ProductEdit(int id)
    {
        var result = await _productsService.GetProductById(id);

        IncludeMessages();

        return View("Edit", result);
    }

    [HttpPost]
    public async Task<IActionResult> EditProduct(ProductModel user)
    {
        if (!VerifyModelState(user))
            return View("Edit", user.Id);

        var result = await _productsService.UpdateProduct(user);

        return await Index();
    }

    [HttpGet("ProductDelete/{id}/{name}")]
    public IActionResult ProductDelete(int id, string name)
    {
        var result = new ProductModel() { Id = id, Name = name };

        IncludeMessages();

        return View("Delete", result);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteProduct(int id)
    {
        var result = await _productsService.DeleteProduct(id);

        IncludeMessages();

        return await Index();
    }

    private bool VerifyModelState(ProductModel user)
    {
        if (!ModelState.IsValid)
        {
            LogModelErrors();
            return false;
        }

        return true;
    }

    private bool VerifyModelState(ProductCreateModel user)
    {
        if (!ModelState.IsValid)
        {
            LogModelErrors();
            return false;
        }

        return true;
    }

    private void LogModelErrors()
    {
        foreach (var state in ModelState)
        {
            foreach (var error in state.Value.Errors)
            {
                _notifierService.AddLog(error.ErrorMessage);
            }
        }

        IncludeMessages();
    }

    private void IncludeMessages()
    {
        if (_notifierService.HasMessages())
        {
            var logs = _notifierService.GetLog();
            ViewData["ErrorLogs"] = logs;
        }
    }
}

microservicAPI/UI/UI/Controllers/UsersController.cs
namespace UI.Controllers;

public class UsersController : Controller
{
    private readonly IUserService _userService;
    private readonly INotifierService _notifierService;

    public UsersController(IUserService userService, INotifierService notifierService)
    {
        _userService = userService;
        _notifierService = notifierService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var result = await _userService.GetAll();
        IncludeMessages();

        return View("Index", result);
    }

    [HttpGet("UserDetails/{id}")]
    public async Task<IActionResult> UserDetails(int id)
    {
        var result = await _userService.GetUserById(id);

        IncludeMessages();

        return View("Details", result);
    }

    [HttpGet]
    public ActionResult Create()
    {
        return View("Create");
    }

    [HttpPost]
    public async Task<IActionResult> CreateUser(UserBaseModel user)
    {
        if (!VerifyModelState(user))
            return Create();

        var result = await _userService.CreateUser(user);

        return await Index();
    }

    [HttpGet("UserEdit/{id}")]
    public async Task<IActionResult> UserEdit(int id)
    {
        var result = await _userService.GetUserById(id);

        IncludeMessages();

        return View("Edit", result);
    }

    [HttpPost]
    public async Task<IActionResult> EditUser(UserModel user)
    {
        if (!VerifyModelState(user))
            return View("Edit", user.Id);

        var result = await _userService.UpdateUser(user);

        return await Index();
    }

    [HttpGet("UserDelete/{id}/{name}")]
    public IActionResult UserDelete(int id, string name)
    {
        var result = new UserModel() { Id = id, Name = name };

        IncludeMessages();

        return View("Delete", result);
    }

    [HttpPost]
    public async Task<IActionResult> DeleteUser(int id)
    {
        var result = await _userService.DeleteUser(id);

        IncludeMessages();

        return await Index();
    }

    private bool VerifyModelState(UserBaseModel user)
    {
        if (!ModelState.IsValid)
        {
            LogModelErrors();
            return false;
        }

        return true;
    }

    private bool VerifyModelState(UserModel user)
    {
        if (!ModelState.IsValid)
        {
            LogModelErrors();
            return false;
        }

        return true;
    }

    private void LogModelErrors()
    {
        foreach (var state in ModelState)
        {
            foreach (var error in state.Value.Errors)
            {
                _notifierService.AddLog(error.ErrorMessage);
            }
        }

        IncludeMessages();
    }

    private void IncludeMessages()
    {
        if (_notifierService.HasMessages())
        {
            var logs = _notifierService.GetLog();
            ViewData["ErrorLogs"] = logs;
        }
    }
}

microservicAPI/UI/UI/Controllers/WeatherController.cs
namespace UI.Controllers;

public class WeatherController : Controller
{
    private readonly IWeatherService _weatherService;

    public WeatherController(IWeatherService weatherService)
    {
        _weatherService = weatherService;
    }

    public async Task<IActionResult> Index()
    {
        ViewData["Title"] = "Weather";

        var result = await _weatherService.GetAll();

        return View("Index", result);
    }

    public async Task<IActionResult> Details(string city)
    {
        ViewData["Title"] = "Weather Details";

        var result = await _weatherService.GetByCity(city);

        return View("Details", result);
    }
}

microservicAPI/UI/UI/Views/Home/Index.cshtml
@page

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

microservicAPI/UI/UI/Views/Products/Create.cshtml
@model Shared.ViewModels.ProductCreateModel
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}
<h2>Create New Product</h2>
<br />
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<form method="post" asp-action="CreateProduct">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" type="number"/>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Create</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

microservicAPI/UI/UI/Views/Products/Delete.cshtml
@model Shared.ViewModels.ProductModel
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}
<h2>Delete Product</h2>
<br />
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<p>Are you sure you want to delete the product <strong>@Model.Name</strong>?</p>
<br />
<form method="post" action="@Url.Action("DeleteProduct")">
    <input type="hidden" name="Id" value="@Model.Id"/>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="@Url.Action("Index")" class="btn btn-secondary">Cancel</a>
</form>

microservicAPI/UI/UI/Views/Products/Details.cshtml
@model Shared.ViewModels.ProductModel
@{
    ViewData["Title"] = "Product Details";
    var errorLogs = ViewData["ErrorLogs"] as string;
}
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
   
<h2>Product Details for @Model.Name</h2>
<br />
<div>
    <p>ID: @Model.Id</p>
    <p>Name: @Model.Name</p>
    <p>Description: @Model.Description</p>
    <p>Price: @Model.Price</p>
    <p>Created: @Model.Created</p>
    <p>Updated: @Model.Updated</p>
    <br />
    <a href="@Url.Action("Index")" class="btn btn-primary">Back to List</a>
</div>

microservicAPI/UI/UI/Views/Products/Edit.cshtml
@model Shared.ViewModels.ProductModel
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}

<h2>Edit User</h2>
<br />
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<form method="post" asp-action="EditProduct">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" type="number" required />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

microservicAPI/UI/UI/Views/Products/Index.cshtml
@model List<Shared.ViewModels.ProductModel>
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}

<div class="text-center">
    <h1 class="display-4">Welcome to products page</h1>
</div>
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<div class="d-flex justify-content-end mb-3">
    <a href="@Url.Action("Create", "Products")" class="btn btn-primary">Create New Product</a>
</div>
<div>
    <h2>Product List</h2>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Created</th>
                <th>Updated</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td>@product.Id</td>
                    <td>@product.Name</td>
                    <td>@product.Description</td>
                    <td>@product.Price</td>
                    <td>@product.Created</td>
                    <td>@product.Updated</td>
                    <td>
                        <a href="@Url.Action("ProductDetails", new { id = product.Id })" class="btn btn-info">Details</a>
                        <a href="@Url.Action("ProductEdit", new { id = product.Id })" class="btn btn-warning">Edit</a>
                        <a href="@Url.Action("ProductDelete", new { id = product.Id, name = product.Name })" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

microservicAPI/UI/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Microservice UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")" >Microservice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index", "Home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index", "Weather")">Weather</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index", "Users")">Users</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Index", "Products")">Products</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Privacy", "Home")">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("Error", "Home")">Error</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Microservice UI - <a href="@Url.Action("Privacy", "Home")">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

microservicAPI/UI/UI/Views/Users/Create.cshtml
@model Shared.ViewModels.UserBaseModel
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}
<h2>Create New User</h2>
<br />
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<form method="post" asp-action="CreateUser">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Age"></label>
        <input asp-for="Age" class="form-control" type="number" required />
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" type="email" required />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="IsSysAdmin"></label>
        <input asp-for="IsSysAdmin" class="form-check-input" type="checkbox" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Create</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

microservicAPI/UI/UI/Views/Users/Delete.cshtml
@model Shared.ViewModels.UserModel
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}
<h2>Delete User</h2>
<br />
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<p>Are you sure you want to delete the user <strong>@Model.Name</strong>?</p>
<br />
<form method="post" action="@Url.Action("DeleteUser")">
    <input type="hidden" name="Id" value="@Model.Id"/>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="@Url.Action("Index")" class="btn btn-secondary">Cancel</a>
</form>

microservicAPI/UI/UI/Views/Users/Details.cshtml
@model Shared.ViewModels.UserModel
@{
    ViewData["Title"] = "User Details";
    var errorLogs = ViewData["ErrorLogs"] as string;
}
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
   
<h2>User Details for @Model.Name</h2>
<br />
<div>
    <p>ID: @Model.Id</p>
    <p>Name: @Model.Name</p>
    <p>Age: @Model.Age</p>
    <p>Email: @Model.Email</p>
    <p>Address: @Model.Address</p>
    <p>City: @Model.City</p>
    <p>Country: @Model.Country</p>
    <p>Postal Code: @Model.PostalCode</p>
    <p>Is Sys Admin: @Model.IsSysAdmin</p>
    <p>ApiKey: @Model.ApiKey</p>
    <br />
    <a href="@Url.Action("Index")" class="btn btn-primary">Back to List</a>
</div>

microservicAPI/UI/UI/Views/Users/Edit.cshtml
@model Shared.ViewModels.UserModel
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}

<h2>Edit User</h2>
<br />
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<form method="post" asp-action="EditUser">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="ApiKey" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Age"></label>
        <input asp-for="Age" class="form-control" type="number" required />
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" type="email" required />
    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="City"></label>
        <input asp-for="City" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Country"></label>
        <input asp-for="Country" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <input asp-for="PostalCode" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="IsSysAdmin"></label>
        <input asp-for="IsSysAdmin" class="form-check-input" type="checkbox" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
</form>

microservicAPI/UI/UI/Views/Users/Index.cshtml
@model List<Shared.ViewModels.UserModel>
@{
    var errorLogs = ViewData["ErrorLogs"] as string;
}

<div class="text-center">
    <h1 class="display-4">Welcome to users page</h1>
</div>
@if (!string.IsNullOrEmpty(errorLogs))
{
    <div class="alert alert-danger" role="alert">
        @errorLogs
    </div>
}
<div class="d-flex justify-content-end mb-3">
    <a href="@Url.Action("Create", "Users")" class="btn btn-primary">Create New User</a>
</div>
<div>
    <h2>User List</h2>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Age</th>
                <th>Is Admin</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model)
            {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.Name</td>
                    <td>@user.Email</td>
                    <td>@user.Age</td>
                    <td>@user.IsSysAdmin</td>
                    <td>
                        <a href="@Url.Action("UserDetails", new { id = user.Id })" class="btn btn-info">Details</a>
                        <a href="@Url.Action("UserEdit", new { id = user.Id })" class="btn btn-warning">Edit</a>
                        <a href="@Url.Action("UserDelete", new { id = user.Id, name = user.Name })" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

microservicAPI/UI/UI/Views/Weather/Details.cshtml
@model Shared.ViewModels.WeatherModel
@{
    ViewData["Title"] = "Weather Details";
}

<h1>Weather</h1>
<br />
<div>
    <h3>Weather Details</h3>
    <br />
    <p>City: @Model.City</p>
    <p>Temperature: @Model.Temperature °C</p>
    <p>Description: @Model.Description</p>
    <br />
    <a href="@Url.Action("Index","Weather")" class="btn btn-primary">Back to List</a>
</div>

microservicAPI/UI/UI/Views/Weather/Index.cshtml
@model List<Shared.ViewModels.WeatherModel>
@{
    ViewData["Title"] = "Weather page";
}

<h1>Weather</h1>
<br />
<div>
    <h2>Available Cities</h2>
    <br />
    <ul>
        @foreach (var weather in Model)
        {
            <li>
                <a href="@Url.Action("Details", new { city = weather.City })">@weather.City</a>
            </li>
        }
    </ul>
</div>